extends SceneTree
const Model = preload("res://scripts/encounter_state.gd")
const Geography = preload("res://scripts/planet_geography.gd")
var checks: int = 0
var failures: int = 0
func _initialize() -> void: call_deferred("run")
func check(value: bool, message: String) -> void:
	checks += 1
	if not value: failures += 1; printerr("FAIL: "+message)

func run() -> void:
	var model := Model.new()
	var before: Dictionary = model.state.duplicate(true)
	check(not model.start_survey().is_empty() and model.state == before,"Surface cannot commission an orbital survey or spend energy")
	model.change_flight_mode("orbit")
	model.state.energy = 19
	check(not model.start_survey().is_empty() and model.state.energy == 19,"Survey validates energy before mutation")
	model.state.energy = 100
	check(model.start_survey().is_empty() and model.state.energy == 80,"Survey spends exactly 20 energy")
	check(not model.start_survey().is_empty() and model.state.energy == 80,"Repeated survey command cannot double charge")
	for i: int in range(5): model.tick()
	check(model.state.survey_ticks == 5 and model.state.survey_active,"Survey advances on fixed orbital ticks")
	var path: String = "res://artifacts/planet_survey.json"
	model.save_to(path)
	var restored := Model.new()
	check(restored.load_from(path) == OK and restored.state == model.state,"Save/load preserves an in-progress orbital survey")
	model.change_flight_mode("surface")
	for i: int in range(8): model.tick()
	check(model.state.survey_ticks == 5 and model.state.survey_active,"Landing suspends survey work without discarding it")
	model.change_flight_mode("orbit")
	for i: int in range(7): model.tick()
	for i: int in range(7): restored.tick()
	check(model.state.survey_ticks == 12 and not model.state.survey_active,"Survey completes once after twelve orbital ticks")
	check(model.state.scanned.is_empty(),"Charting geography does not reveal ground discoveries")
	check(restored.state.survey_ticks == 12,"Restored survey resumes from its actual saved progress")
	check(model.state.history.filter(func(entry: Dictionary) -> bool: return entry.id == "orbital_chart").size() == 1,"Orbital chart records exactly one chronicle milestone")
	before = model.state.duplicate(true)
	check(not model.start_survey().is_empty() and model.state == before,"Completed charts cannot be farmed")
	var legacy: Dictionary = Model.fresh()
	legacy.version = 2
	legacy.marks = 72
	legacy.erase("planet_id")
	legacy.erase("survey_ticks")
	legacy.erase("survey_active")
	var file := FileAccess.open(path,FileAccess.WRITE)
	file.store_string(JSON.stringify(legacy))
	file.close()
	check(restored.load_from(path) == OK and restored.state.marks == 72 and restored.state.survey_ticks == 0,"Version 2 migration preserves earned stock and starts with uncharted geography")
	legacy = Model.fresh()
	legacy.survey_ticks = 99
	file = FileAccess.open(path,FileAccess.WRITE)
	file.store_string(JSON.stringify(legacy))
	file.close()
	before = restored.state.duplicate(true)
	check(restored.load_from(path) == ERR_INVALID_DATA and restored.state == before,"Invalid chart progress cannot overwrite current state")
	check(Geography.direction(0,90).is_equal_approx(Vector3.RIGHT),"Longitude convention is explicit and stable")
	check(Geography.seed_offset(1948) == Geography.seed_offset(1948),"The same planet seed produces the same geography offset")
	var scene: Node3D = load("res://scenes/encounter.tscn").instantiate()
	root.add_child(scene)
	await process_frame
	scene.set_process(false)
	scene.set_physics_process(false)
	scene.model = Model.new()
	scene.save_path = "res://artifacts/atlas_ui_test.json"
	scene._toggle_planet_map()
	var atlas: Control = scene.planet_map
	check(atlas.visible and not scene.popup.visible,"Atlas opens separately from inventory drawers")
	check(atlas.survey_button.disabled,"Surface map explains that survey requires orbit")
	var instant: int = scene.model.state.time
	scene._process(2)
	check(scene.model.state.time == instant,"Atlas inspection does not advance survey or economy")
	check(atlas.globe.site_marker.position.normalized().is_equal_approx(scene.orbit.planet.site_marker.position.normalized()),"Map and orbital markers use the same planet-fixed coordinates")
	var shader_offset: Vector3 = atlas.globe.material.get_shader_parameter("geography_offset")
	check(shader_offset.is_equal_approx(scene.orbit.planet.material.get_shader_parameter("geography_offset")),"Map and orbital geography share the same seeded material")
	atlas.globe.rotation.y = PI
	check(not atlas.marker_visible(atlas.globe.site_marker),"Back-side site cannot display through the planet")
	check(not atlas.pick_site(Vector2.ZERO),"Back-side site cannot be picked through the globe")
	atlas.focus_site()
	check(atlas.marker_visible(atlas.globe.site_marker),"Site focus rotates its fixed position into view")
	atlas.set_layer(true)
	check(atlas.globe.material.get_shader_parameter("survey_layer"),"Survey layer updates the rendered globe")
	scene._map_travel("invented_site")
	check(not scene.navigating and atlas.visible,"Unknown destinations cannot issue travel commands")
	scene._toggle_planet_map()
	scene._change_flight_mode("orbit")
	scene._toggle_planet_map()
	check(not atlas.survey_button.disabled,"Survey becomes available in orbit")
	atlas.survey_requested.emit()
	check(not atlas.visible and scene.model.state.survey_active,"Survey action returns to running flight")
	for i: int in range(6): scene.model.tick()
	scene._toggle_planet_map()
	check(is_equal_approx(atlas.chart_progress,0.5),"Atlas reads saved survey progress instead of its own timer")
	atlas.travel_requested.emit("morrow_basin")
	check(not atlas.visible and scene.landing and scene.model.state.flight_mode == "orbit","Map landing issues an approach rather than instant teleport")
	for i: int in range(360): scene._physics_process(1.0/60)
	check(scene.model.state.flight_mode == "surface" and scene.model.state.survey_ticks == 6,"Map approach returns to the existing basin without resetting chart progress")
	scene._toggle_pause()
	scene._toggle_planet_map()
	check(atlas.travel_button.disabled and atlas.survey_button.disabled,"Explicit player pause disables map commands")
	scene._toggle_planet_map()
	check(scene.paused,"Closing atlas preserves explicit player pause")
	scene._show_popup("cargo")
	check(not atlas.visible and scene.popup.visible,"Inventory and atlas are mutually exclusive")
	scene.free()
	print("Planet map assertions: ",checks,"; failures: ",failures)
	quit(0 if failures == 0 else 1)
